// <auto-generated>
// This file was auto-generated. Do not modify manually.
// </auto-generated>
using System;
using System.Linq;
using System.Web.Http;
using WebApplicationApi.Models;

namespace WebApplicationApi.Controllers.Base
{
    public abstract class BaseApiController<TEntity, TViewModel, TKey> : ApiController
        where TEntity : class, new()
    {
        protected DataClassesDatabaseDataContext db = new DataClassesDatabaseDataContext();

        [HttpGet]
        public virtual IHttpActionResult List(int page = 1, int pageSize = 20)
        {
            if (page < 1) page = 1;
            if (pageSize < 1) pageSize = 20;
            if (pageSize > 100) pageSize = 100;

            var query = GetQuery();
            var total = query.Count();
            var items = query.Skip((page - 1) * pageSize).Take(pageSize).ToList()
                             .Select(MapToViewModel).ToList();

            return Ok(new {
                Total = total,
                Page = page,
                PageSize = pageSize,
                TotalPages = (int)Math.Ceiling((double)total / pageSize),
                Data = items
            });
        }

        [HttpGet]
        public virtual IHttpActionResult Details(TKey id)
        {
            var entity = FindEntity(id);
            if (entity == null) return NotFound();
            return Ok(MapToViewModel(entity));
        }

        [HttpPost]
        public virtual IHttpActionResult Create(TViewModel model)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);
            var entity = MapToEntity(model);
            InsertEntity(entity);
            db.SubmitChanges();
            return Ok(MapToViewModel(entity));
        }

        [HttpPut]
        public virtual IHttpActionResult Update(TKey id, TViewModel model)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);
            var entity = FindEntity(id);
            if (entity == null) return NotFound();
            UpdateEntity(entity, model);
            db.SubmitChanges();
            return Ok(MapToViewModel(entity));
        }

        [HttpDelete]
        public virtual IHttpActionResult Delete(TKey id)
        {
            var entity = FindEntity(id);
            if (entity == null) return NotFound();
            DeleteEntity(entity);
            db.SubmitChanges();
            return Ok(new { Message = "Deleted successfully" });
        }

        protected abstract IQueryable<TEntity> GetQuery();
        protected abstract TEntity FindEntity(TKey id);
        protected abstract TViewModel MapToViewModel(TEntity entity);
        protected abstract TEntity MapToEntity(TViewModel model);
        protected abstract void UpdateEntity(TEntity entity, TViewModel model);
        protected abstract void InsertEntity(TEntity entity);
        protected abstract void DeleteEntity(TEntity entity);
    }
}
