//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC_StoreDetails
    {
        public int ID { get; set; }
        public string StoreName { get; set; }
        public string Logo { get; set; }
        public string AboutStore { get; set; }
        public string ReturnConditions { get; set; }
        public string Instagram { get; set; }
        public string Telegram { get; set; }
        public string twitter { get; set; }
        public string Facebook { get; set; }
        public string Pinterest { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string SupportNo { get; set; }
        public string SupportHours { get; set; }
    }
}
