//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_Addresses
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string FullName { get; set; }
        public string MobileNo { get; set; }
    
        public virtual BD_Cities BD_Cities { get; set; }
        public virtual SD_Users SD_Users { get; set; }
    }
}
