//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_Coupons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_Coupons()
        {
            this.SD_Transactions = new HashSet<SD_Transactions>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> CouponPercent { get; set; }
        public Nullable<int> MaxRialValue { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_Transactions> SD_Transactions { get; set; }
    }
}
