//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_ShoppingBasketObjects
    {
        public int ID { get; set; }
        public Nullable<int> ShoppingBasketID { get; set; }
        public Nullable<int> ProductChargeID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> OldPrice { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual SD_ProductCharges SD_ProductCharges { get; set; }
        public virtual SD_ShoppingBasket SD_ShoppingBasket { get; set; }
    }
}
