//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_Transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_Transactions()
        {
            this.SD_SendBoxs = new HashSet<SD_SendBoxs>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ShoppingBasketID { get; set; }
        public Nullable<int> SumTaxAmount { get; set; }
        public Nullable<int> DiscountCodeID { get; set; }
        public Nullable<int> DiscountAmount { get; set; }
        public Nullable<int> SendAmount { get; set; }
        public Nullable<int> SumShoppingBasketPrice { get; set; }
        public Nullable<int> SumShoppingBasketDiscount { get; set; }
        public Nullable<int> AmountForPay { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public string PaymentTrackingNo { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual SD_Coupons SD_Coupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_SendBoxs> SD_SendBoxs { get; set; }
        public virtual SD_ShoppingBasket SD_ShoppingBasket { get; set; }
    }
}
