//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_Votes
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProductChargePropertiesID { get; set; }
        public Nullable<int> Star { get; set; }
        public string Comment { get; set; }
    
        public virtual SD_ProductChargesProperties SD_ProductChargesProperties { get; set; }
        public virtual SD_Users SD_Users { get; set; }
    }
}
