//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Admin_TransactionID
    {
        public int ID { get; set; }
        public int TransactionID { get; set; }
        public int ShoppingBasketID { get; set; }
        public string BasketType { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> SumShoppingBasketPrice { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentTrackingNo { get; set; }
        public string Status { get; set; }
    }
}
