//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Site_ProductDetails_SimilarProductInSize
    {
        public int ID { get; set; }
        public int ProductChargePropertiesID { get; set; }
        public string Name { get; set; }
        public string BuyInvoiceNumber { get; set; }
        public Nullable<int> PercentInterest { get; set; }
        public Nullable<int> PercentWages { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> RemainingCount { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
    }
}
