//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_User_Baskets
    {
        public int ShoppingBasketID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BasketStatusID { get; set; }
        public string BasketStatus { get; set; }
    }
}
