//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Admin_ProductChargeID
    {
        public int ProductChargeID { get; set; }
        public string Product { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string BuyInvoiceNumber { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public Nullable<int> BuyCount { get; set; }
    }
}
