//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Site_ProductDetails_SendPrices
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Product { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string ProductDescription { get; set; }
        public int SendID { get; set; }
        public string Send { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Country { get; set; }
        public Nullable<int> StateID { get; set; }
        public string State { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
