//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStoreAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Site_ProductDetails_Sizes
    {
        public int ID { get; set; }
        public int ProductChargePropertiesID { get; set; }
        public string SizeTitle { get; set; }
        public string SizeDescription { get; set; }
        public string SizeValue { get; set; }
        public string SizeValueDescription { get; set; }
    }
}
